### ISSUE TITLE
implement CALLCODE

### ISSUE THREAD

**Issue by mbrock** [dapphub/hsevm#2]
Should be easy.

**Comment by VoR0220** [comment]
Sorry for poking my head in, but is this necessary? Would seem that CALLCODE is essentially retired.

**Comment by rainbreak** [comment]
@VoR0220 it's necessary if you want to do testing of previously deployed objects that use it.

**Comment by VoR0220** [comment]
There hasn't been a previously deployed contract with that opcode since before 0.3.6. We're now at 0.4.13...

**Comment by mbrock** [comment]
Yeah, it's probably better to leave it as an error. If someone really wants it they can implement it. :)
